/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    customers: CustomerAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    companies: Company;
    categories: Category;
    products: Product;
    customers: Customer;
    orders: Order;
    quotes: Quote;
    'cart-items': CartItem;
    'ai-conversations': AiConversation;
    'ai-messages': AiMessage;
    'product-embeddings': ProductEmbedding;
    'knowledge-base': KnowledgeBase;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    companies: CompaniesSelect<false> | CompaniesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    quotes: QuotesSelect<false> | QuotesSelect<true>;
    'cart-items': CartItemsSelect<false> | CartItemsSelect<true>;
    'ai-conversations': AiConversationsSelect<false> | AiConversationsSelect<true>;
    'ai-messages': AiMessagesSelect<false> | AiMessagesSelect<true>;
    'product-embeddings': ProductEmbeddingsSelect<false> | ProductEmbeddingsSelect<true>;
    'knowledge-base': KnowledgeBaseSelect<false> | KnowledgeBaseSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'group-settings': GroupSetting;
  };
  globalsSelect: {
    'group-settings': GroupSettingsSelect<false> | GroupSettingsSelect<true>;
  };
  locale: null;
  user:
    | (User & {
        collection: 'users';
      })
    | (Customer & {
        collection: 'customers';
      });
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'super-admin' | 'admin' | 'manager' | 'staff';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: number;
  name: string;
  nameAr: string;
  shortName?: string | null;
  shortNameAr?: string | null;
  tagline?: string | null;
  taglineAr?: string | null;
  description?: string | null;
  descriptionAr?: string | null;
  companyType: 'plastics' | 'electronics' | 'manufacturing' | 'recycling';
  foundedYear?: number | null;
  logo?: (number | null) | Media;
  logoDark?: (number | null) | Media;
  heroImage?: (number | null) | Media;
  galleryImages?:
    | {
        image: number | Media;
        caption?: string | null;
        captionAr?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Hex color code (e.g., #0066CC)
   */
  primaryColor?: string | null;
  /**
   * Hex color code (e.g., #FF5500)
   */
  secondaryColor?: string | null;
  accentColor?: string | null;
  backgroundColor?: string | null;
  country: 'egypt' | 'saudi' | 'uae';
  city?: string | null;
  cityAr?: string | null;
  address?: string | null;
  addressAr?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  googleMapsUrl?: string | null;
  phones?:
    | {
        number: string;
        label?: string | null;
        isWhatsApp?: boolean | null;
        id?: string | null;
      }[]
    | null;
  emails?:
    | {
        email: string;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  website?: string | null;
  socialLinks?: {
    facebook?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
    twitter?: string | null;
    youtube?: string | null;
  };
  businessHours?: {
    /**
     * e.g., 9:00 AM - 6:00 PM
     */
    weekdays?: string | null;
    weekends?: string | null;
    note?: string | null;
    noteAr?: string | null;
  };
  vision?: string | null;
  visionAr?: string | null;
  mission?: string | null;
  missionAr?: string | null;
  values?:
    | {
        value: string;
        valueAr?: string | null;
        description?: string | null;
        descriptionAr?: string | null;
        id?: string | null;
      }[]
    | null;
  services?:
    | {
        name: string;
        nameAr?: string | null;
        description?: string | null;
        descriptionAr?: string | null;
        /**
         * Lucide icon name (e.g., camera, shield, flame)
         */
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  certifications?:
    | {
        name: string;
        nameAr?: string | null;
        logo?: (number | null) | Media;
        year?: number | null;
        id?: string | null;
      }[]
    | null;
  metaTitle?: string | null;
  metaTitleAr?: string | null;
  metaDescription?: string | null;
  metaDescriptionAr?: string | null;
  ogImage?: (number | null) | Media;
  /**
   * Used for subdomain routing (e.g., industry, talah, polymers)
   */
  slug: string;
  order?: number | null;
  /**
   * Is this the parent/holding company?
   */
  isParent?: boolean | null;
  active?: boolean | null;
  showInMainNav?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  nameAr: string;
  slug: string;
  description?: string | null;
  descriptionAr?: string | null;
  image?: (number | null) | Media;
  company?: (number | null) | Company;
  parent?: (number | null) | Category;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  nameAr: string;
  slug: string;
  sku?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  descriptionAr?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  price: number;
  /**
   * Original price for showing discounts
   */
  compareAtPrice?: number | null;
  costPrice?: number | null;
  stock?: number | null;
  lowStockThreshold?: number | null;
  trackInventory?: boolean | null;
  /**
   * Select which company this product belongs to
   */
  company: number | Company;
  category: number | Category;
  brand?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  images?:
    | {
        image: number | Media;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  datasheet?: (number | null) | Media;
  productType: 'cctv' | 'access-control' | 'intercom' | 'pbx' | 'nurse-call' | 'fire-alarm' | 'gps' | 'raw-material';
  specifications?:
    | {
        key: string;
        value: string;
        keyAr?: string | null;
        valueAr?: string | null;
        id?: string | null;
      }[]
    | null;
  cctvSpecs?: {
    resolution?: string | null;
    cameraType?: ('IP' | 'AHD' | 'TVI' | 'CVI') | null;
    nightVision?: string | null;
    indoorOutdoor?: ('indoor' | 'outdoor' | 'both') | null;
    poe?: boolean | null;
    audioSupport?: boolean | null;
  };
  accessControlSpecs?: {
    maxUsers?: number | null;
    fingerprintCapacity?: number | null;
    faceCapacity?: number | null;
    cardSupport?: boolean | null;
    wifiSupport?: boolean | null;
    attendanceReport?: boolean | null;
  };
  rawMaterialSpecs?: {
    materialType?: ('PP' | 'PE' | 'HDPE' | 'LDPE' | 'PVC' | 'Other') | null;
    grade?: string | null;
    mfi?: string | null;
    minOrderQuantity?: number | null;
    unitOfMeasure?: ('kg' | 'ton' | 'bag') | null;
  };
  metaTitle?: string | null;
  metaDescription?: string | null;
  status: 'draft' | 'published' | 'archived';
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  firstName: string;
  lastName: string;
  phone: string;
  company?: string | null;
  customerType?: ('individual' | 'business') | null;
  addresses?:
    | {
        /**
         * e.g., Home, Office
         */
        label?: string | null;
        fullName?: string | null;
        phone?: string | null;
        address: string;
        city: string;
        governorate: string;
        isDefault?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber?: string | null;
  customer: number | Customer;
  items: {
    product: number | Product;
    quantity: number;
    priceAtTime: number;
    subtotal: number;
    id?: string | null;
  }[];
  subtotal: number;
  shippingCost?: number | null;
  discount?: number | null;
  total: number;
  shippingAddress: {
    fullName: string;
    phone: string;
    address: string;
    city: string;
    governorate: string;
  };
  payment?: {
    method?: ('bank-transfer' | 'vodafone-cash' | 'card' | 'cash-on-delivery') | null;
    status?: ('pending' | 'paid' | 'failed' | 'refunded') | null;
    transactionId?: string | null;
    paidAt?: string | null;
  };
  status: 'pending' | 'confirmed' | 'processing' | 'shipped' | 'delivered' | 'cancelled';
  customerNotes?: string | null;
  adminNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes".
 */
export interface Quote {
  id: number;
  quoteNumber?: string | null;
  customer?: (number | null) | Customer;
  contactName?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  companyName?: string | null;
  items?:
    | {
        product?: (number | null) | Product;
        quantity: number;
        customRequest?: string | null;
        id?: string | null;
      }[]
    | null;
  message?: string | null;
  status: 'pending' | 'quoted' | 'accepted' | 'rejected';
  quotedPrice?: number | null;
  adminResponse?: string | null;
  validUntil?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cart-items".
 */
export interface CartItem {
  id: number;
  customer?: (number | null) | Customer;
  /**
   * For guest carts before login
   */
  sessionId?: string | null;
  product: number | Product;
  quantity: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-conversations".
 */
export interface AiConversation {
  id: number;
  /**
   * Unique session identifier for this conversation
   */
  sessionId: string;
  /**
   * Linked customer (null for guest conversations)
   */
  customer?: (number | null) | Customer;
  /**
   * Auto-generated from first message
   */
  title?: string | null;
  status: 'active' | 'archived' | 'deleted';
  /**
   * Additional metadata (locale, device, userAgent, etc.)
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Total number of messages in this conversation
   */
  messageCount?: number | null;
  /**
   * Timestamp of the last message
   */
  lastMessageAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-messages".
 */
export interface AiMessage {
  id: number;
  /**
   * The conversation this message belongs to
   */
  conversation: number | AiConversation;
  /**
   * Who sent this message
   */
  role: 'user' | 'assistant' | 'system';
  /**
   * The message content
   */
  content: string;
  /**
   * Function calls made by the AI in this message
   */
  functionCalls?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Results from function calls
   */
  functionResults?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Additional metadata (model, temperature, etc.)
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Number of tokens used for this message
   */
  tokensUsed?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Vector embeddings for products used in AI-powered search and recommendations
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-embeddings".
 */
export interface ProductEmbedding {
  id: number;
  /**
   * The product this embedding represents
   */
  product: number | Product;
  /**
   * Vector embedding (768 dimensions for text-embedding-004)
   */
  embedding?:
    | {
        value?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The original text that was embedded (name + description + specs)
   */
  text?: string | null;
  /**
   * Language of the embedded text
   */
  locale: 'ar' | 'en';
  /**
   * Additional metadata (category, brand, price_range, etc.)
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Company policies, FAQs, and guides used by the AI assistant
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge-base".
 */
export interface KnowledgeBase {
  id: number;
  /**
   * Title of the knowledge base entry
   */
  title: string;
  /**
   * Unique slug for this entry (e.g., shipping-policy, faq-returns)
   */
  slug: string;
  /**
   * The content in markdown format
   */
  content: string;
  /**
   * Type of knowledge base entry
   */
  type: 'policy' | 'faq' | 'guide';
  /**
   * Category (shipping, return, warranty, payment, installation, etc.)
   */
  category?: string | null;
  /**
   * Vector embedding for semantic search (array of numbers)
   */
  embedding?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Language of this entry
   */
  locale: 'ar' | 'en';
  /**
   * Additional metadata
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Whether this entry is active and should be used by the AI
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'companies';
        value: number | Company;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'quotes';
        value: number | Quote;
      } | null)
    | ({
        relationTo: 'cart-items';
        value: number | CartItem;
      } | null)
    | ({
        relationTo: 'ai-conversations';
        value: number | AiConversation;
      } | null)
    | ({
        relationTo: 'ai-messages';
        value: number | AiMessage;
      } | null)
    | ({
        relationTo: 'product-embeddings';
        value: number | ProductEmbedding;
      } | null)
    | ({
        relationTo: 'knowledge-base';
        value: number | KnowledgeBase;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies_select".
 */
export interface CompaniesSelect<T extends boolean = true> {
  name?: T;
  nameAr?: T;
  shortName?: T;
  shortNameAr?: T;
  tagline?: T;
  taglineAr?: T;
  description?: T;
  descriptionAr?: T;
  companyType?: T;
  foundedYear?: T;
  logo?: T;
  logoDark?: T;
  heroImage?: T;
  galleryImages?:
    | T
    | {
        image?: T;
        caption?: T;
        captionAr?: T;
        id?: T;
      };
  primaryColor?: T;
  secondaryColor?: T;
  accentColor?: T;
  backgroundColor?: T;
  country?: T;
  city?: T;
  cityAr?: T;
  address?: T;
  addressAr?: T;
  latitude?: T;
  longitude?: T;
  googleMapsUrl?: T;
  phones?:
    | T
    | {
        number?: T;
        label?: T;
        isWhatsApp?: T;
        id?: T;
      };
  emails?:
    | T
    | {
        email?: T;
        label?: T;
        id?: T;
      };
  website?: T;
  socialLinks?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        linkedin?: T;
        twitter?: T;
        youtube?: T;
      };
  businessHours?:
    | T
    | {
        weekdays?: T;
        weekends?: T;
        note?: T;
        noteAr?: T;
      };
  vision?: T;
  visionAr?: T;
  mission?: T;
  missionAr?: T;
  values?:
    | T
    | {
        value?: T;
        valueAr?: T;
        description?: T;
        descriptionAr?: T;
        id?: T;
      };
  services?:
    | T
    | {
        name?: T;
        nameAr?: T;
        description?: T;
        descriptionAr?: T;
        icon?: T;
        id?: T;
      };
  certifications?:
    | T
    | {
        name?: T;
        nameAr?: T;
        logo?: T;
        year?: T;
        id?: T;
      };
  metaTitle?: T;
  metaTitleAr?: T;
  metaDescription?: T;
  metaDescriptionAr?: T;
  ogImage?: T;
  slug?: T;
  order?: T;
  isParent?: T;
  active?: T;
  showInMainNav?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  nameAr?: T;
  slug?: T;
  description?: T;
  descriptionAr?: T;
  image?: T;
  company?: T;
  parent?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  nameAr?: T;
  slug?: T;
  sku?: T;
  description?: T;
  descriptionAr?: T;
  price?: T;
  compareAtPrice?: T;
  costPrice?: T;
  stock?: T;
  lowStockThreshold?: T;
  trackInventory?: T;
  company?: T;
  category?: T;
  brand?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  images?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  datasheet?: T;
  productType?: T;
  specifications?:
    | T
    | {
        key?: T;
        value?: T;
        keyAr?: T;
        valueAr?: T;
        id?: T;
      };
  cctvSpecs?:
    | T
    | {
        resolution?: T;
        cameraType?: T;
        nightVision?: T;
        indoorOutdoor?: T;
        poe?: T;
        audioSupport?: T;
      };
  accessControlSpecs?:
    | T
    | {
        maxUsers?: T;
        fingerprintCapacity?: T;
        faceCapacity?: T;
        cardSupport?: T;
        wifiSupport?: T;
        attendanceReport?: T;
      };
  rawMaterialSpecs?:
    | T
    | {
        materialType?: T;
        grade?: T;
        mfi?: T;
        minOrderQuantity?: T;
        unitOfMeasure?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  status?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  phone?: T;
  company?: T;
  customerType?: T;
  addresses?:
    | T
    | {
        label?: T;
        fullName?: T;
        phone?: T;
        address?: T;
        city?: T;
        governorate?: T;
        isDefault?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  customer?: T;
  items?:
    | T
    | {
        product?: T;
        quantity?: T;
        priceAtTime?: T;
        subtotal?: T;
        id?: T;
      };
  subtotal?: T;
  shippingCost?: T;
  discount?: T;
  total?: T;
  shippingAddress?:
    | T
    | {
        fullName?: T;
        phone?: T;
        address?: T;
        city?: T;
        governorate?: T;
      };
  payment?:
    | T
    | {
        method?: T;
        status?: T;
        transactionId?: T;
        paidAt?: T;
      };
  status?: T;
  customerNotes?: T;
  adminNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes_select".
 */
export interface QuotesSelect<T extends boolean = true> {
  quoteNumber?: T;
  customer?: T;
  contactName?: T;
  contactEmail?: T;
  contactPhone?: T;
  companyName?: T;
  items?:
    | T
    | {
        product?: T;
        quantity?: T;
        customRequest?: T;
        id?: T;
      };
  message?: T;
  status?: T;
  quotedPrice?: T;
  adminResponse?: T;
  validUntil?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cart-items_select".
 */
export interface CartItemsSelect<T extends boolean = true> {
  customer?: T;
  sessionId?: T;
  product?: T;
  quantity?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-conversations_select".
 */
export interface AiConversationsSelect<T extends boolean = true> {
  sessionId?: T;
  customer?: T;
  title?: T;
  status?: T;
  metadata?: T;
  messageCount?: T;
  lastMessageAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-messages_select".
 */
export interface AiMessagesSelect<T extends boolean = true> {
  conversation?: T;
  role?: T;
  content?: T;
  functionCalls?: T;
  functionResults?: T;
  metadata?: T;
  tokensUsed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-embeddings_select".
 */
export interface ProductEmbeddingsSelect<T extends boolean = true> {
  product?: T;
  embedding?:
    | T
    | {
        value?: T;
        id?: T;
      };
  text?: T;
  locale?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge-base_select".
 */
export interface KnowledgeBaseSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  type?: T;
  category?: T;
  embedding?: T;
  locale?: T;
  metadata?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "group-settings".
 */
export interface GroupSetting {
  id: number;
  groupName: string;
  groupNameAr: string;
  shortName?: string | null;
  shortNameAr?: string | null;
  slogan?: string | null;
  sloganAr?: string | null;
  description?: string | null;
  descriptionAr?: string | null;
  foundedYear?: number | null;
  mainDomain?: string | null;
  groupLogo?: (number | null) | Media;
  groupLogoDark?: (number | null) | Media;
  heroImage?: (number | null) | Media;
  favicon?: (number | null) | Media;
  vision?: string | null;
  visionAr?: string | null;
  mission?: string | null;
  missionAr?: string | null;
  totalCompanies?: number | null;
  countriesPresence?: number | null;
  totalEmployees?: number | null;
  totalClients?: number | null;
  countries?:
    | {
        name: string;
        nameAr?: string | null;
        /**
         * e.g., 🇪🇬 🇸🇦 🇦🇪
         */
        flag?: string | null;
        id?: string | null;
      }[]
    | null;
  mainEmail?: string | null;
  mainPhone?: string | null;
  whatsapp?: string | null;
  headquarters?: {
    address?: string | null;
    addressAr?: string | null;
    city?: string | null;
    country?: string | null;
  };
  socialLinks?: {
    facebook?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
    twitter?: string | null;
    youtube?: string | null;
  };
  metaTitle?: string | null;
  metaTitleAr?: string | null;
  metaDescription?: string | null;
  metaDescriptionAr?: string | null;
  ogImage?: (number | null) | Media;
  keywords?: string | null;
  keywordsAr?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "group-settings_select".
 */
export interface GroupSettingsSelect<T extends boolean = true> {
  groupName?: T;
  groupNameAr?: T;
  shortName?: T;
  shortNameAr?: T;
  slogan?: T;
  sloganAr?: T;
  description?: T;
  descriptionAr?: T;
  foundedYear?: T;
  mainDomain?: T;
  groupLogo?: T;
  groupLogoDark?: T;
  heroImage?: T;
  favicon?: T;
  vision?: T;
  visionAr?: T;
  mission?: T;
  missionAr?: T;
  totalCompanies?: T;
  countriesPresence?: T;
  totalEmployees?: T;
  totalClients?: T;
  countries?:
    | T
    | {
        name?: T;
        nameAr?: T;
        flag?: T;
        id?: T;
      };
  mainEmail?: T;
  mainPhone?: T;
  whatsapp?: T;
  headquarters?:
    | T
    | {
        address?: T;
        addressAr?: T;
        city?: T;
        country?: T;
      };
  socialLinks?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        linkedin?: T;
        twitter?: T;
        youtube?: T;
      };
  metaTitle?: T;
  metaTitleAr?: T;
  metaDescription?: T;
  metaDescriptionAr?: T;
  ogImage?: T;
  keywords?: T;
  keywordsAr?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}